DetectorID: growth-fy2016a
PreTriggerSamples: 20
PostTriggerSamples: 1000
SamplesInEventPacket: 1000
DownSamplingFactorForSavedWaveform: 1
ChannelEnable: [yes,yes,yes,yes]
TriggerThresholds: [2100, 2100, 2100, 2100]
TriggerCloseThresholds: [2090, 2090, 2090, 2090]
